language: python

sudo: false

cache:
  directories:
  - $HOME/env

notifications:
  email: false

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment

install:
    - pip install -e .

script:
    - export PYTHONPATH="./scripts:$PYTHONPATH"
    - py.test

after_success:
    - coveralls